In [50]:
import numpy as np 
 
 # list vs numpy array

list = [3,4,5]
print("list array",list*2)

arr = np.array([2,45,5])
print("numpy array :" , arr*2)
# in numpy each elements are multiplied by 2 


list array [3, 4, 5, 3, 4, 5]
numpy array : [ 4 90 10]


In [51]:
arr = np.array([2,45,5])
print("array :" , arr)

array : [ 2 45  5]


In [52]:
import numpy as np

arr = np.array([[2,5,5],[3,4,2]])
print("array :" , arr)

array : [[2 5 5]
 [3 4 2]]


In [53]:
zeros = np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [54]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [55]:
twos = np.full((3,4),2)
print(twos)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [56]:
random = np.random.random((3,4))
print(random)

[[0.8362877  0.11371791 0.22840099 0.82625043]
 [0.50537972 0.21711024 0.47042706 0.41970667]
 [0.10705541 0.66085531 0.76740404 0.7481057 ]]


In [57]:
sequence = np.arange(3,54,2)
print(sequence)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53]


Array Properties

arr = np.array([[3,"4",5],[3,7.0,4]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


Array Reshaping

In [58]:
arr = np.arange(10)

print("Reshaped array:" , arr.reshape((2,5)))

print("Flattened array:",arr.flatten())

# returns original array and above flatten , reshape return copy of the array 
print("Ravelled array:",arr.ravel())

print("Transposed array:",arr.T)




Reshaped array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Flattened array: [0 1 2 3 4 5 6 7 8 9]
Ravelled array: [0 1 2 3 4 5 6 7 8 9]
Transposed array: [0 1 2 3 4 5 6 7 8 9]
