In [1]:
import numpy as np

In [5]:
arr_2d = np.array([[3,4,5],[3,5,7]])

print("Specific element:",arr_2d[1,2])
print("Entire row:",arr_2d[1])
print("Entire Column:",arr_2d[: ,2])

Specific element: 7
Entire row: [3 5 7]
Entire Column: [5 7]


# Sorting

In [8]:
#basic sorting

arr = np.array([9,8,6,34,2,5,34,56,12])
print("Sorted array:",np.sort(arr))


arr_2d = np.array([[3,4,5],[6,4,3],[5,67,3]])
#to sort rows 
print("Sorted rows",np.sort(arr_2d,axis=0))

#to sort column
print("Sorted column",np.sort(arr_2d,axis=1))

Sorted array: [ 2  5  6  8  9 12 34 34 56]
Sorted rows [[ 3  4  3]
 [ 5  4  3]
 [ 6 67  5]]
Sorted column [[ 3  4  5]
 [ 3  4  6]
 [ 3  5 67]]


# Filter

In [10]:
num = np.array([3,4,5,6,7,8,9])

print("Odd numbers",num[num%2 != 0])

# we can put whole expression inside []

Odd numbers [3 5 7 9]


## Filter with mask


In [13]:
mask = num<6
print(num[mask])

# we can store whole expression inside variable and use in code 

[3 4 5]


# Indices


In [19]:
numbers = [0,2,4] # stored the indices

print(num[numbers]) # used the indices to find numbers


where_result = np.where(num>6) # get the index of the numbers which are > 6

print("numbers are" , num[where_result]) #used the above index to find numbers which are >6



[3 5 7]
numbers are [7 8 9]


In [22]:
# where existing array ko modify krta hai 

condition_array = np.where(num>5 , num*2  , num) # if num is greater than 5 , multiply it with 2 else print as it is num 
# it works like if num>5 print(mutliply by 2) else num
 
print(condition_array)



[ 3  4  5 12 14 16 18]


# Adding and concatenating arrays


In [ ]:
first = np.array([3,4,5,6])
second = np.array([5,3,6,3])

print(first + second) # here values are added example 3 will be added to 5 = 8 

combined = np.concatenate((first,second))
print(combined) # here arrays are concatenated 


[ 8  7 11  9]
[3 4 5 6 5 3 6 3]
[3 4 5 6 5 3 6 3]


# Array Compatibility

