In [ ]:
import numpy as np 


# Question (medium)

# OpenAI API Error: OPENAI_API_KEY not configured. Please set it in your .env and reload VS Code.


ModuleNotFoundError: No module named 'numpy'

In [2]:
arr = np.array([2,45,5])
print("array :" , arr)

NameError: name 'np' is not defined

In [4]:
arr = np.array([2,45,5])
print("array :" , arr)


NameError: name 'np' is not defined

In [5]:
import numpy as np 

In [7]:
import numpy as np 

In [8]:
import numpy as np

arr = np.array([[2,5,5],[3,4,2]])
print("array :" , arr)

array : [[2 5 5]
 [3 4 2]]


In [10]:
zeros = np.zeros((3,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [19]:
ones = np.ones((3,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [21]:
twos = np.full((3,4),2)
print(twos)

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


In [23]:
random = np.random.random((3,4))
print(random)

[[0.87455243 0.03128703 0.63520032 0.64523932]
 [0.08616955 0.61616756 0.973776   0.44125686]
 [0.20428699 0.68995    0.89134088 0.22190339]]


In [25]:
sequence = np.arange(3,54,2)
print(sequence)

[ 3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49
 51 53]


Array Properties

arr = np.array([[3,"4",5],[3,7.0,4]])

print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)


Array Reshaping

In [41]:
arr = np.arange(10)

print("Reshaped array:" , arr.reshape((2,5)))

print("Flattened array:",arr.flatten())

Reshaped array: [[0 1 2 3 4]
 [5 6 7 8 9]]
Flattened array: [0 1 2 3 4 5 6 7 8 9]
